name: Spring Boot CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test1:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/test1:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
        
      - name: Deploy to Contabo
        env:
          CONTABO_HOST: 89.250.70.43
          CONTABO_USER: root
          CONTABO_PASS: Kyrgyzstanym01!
        run: |
          sshpass -p "$CONTABO_PASS" ssh -o StrictHostKeyChecking=no $CONTABO_USER@$CONTABO_HOST '
            # Pull the latest image
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/test1:latest
            
            # Stop and remove existing container
            docker stop test1 || true
            docker rm test1 || true
            
            # Run new container
            docker run -d \
              --name test1 \
              --restart unless-stopped \
              -p 9091:8080 \
              ${{ secrets.DOCKER_USERNAME }}/test1:latest
              
            # Cleanup
            docker system prune -f
          '

